### ISSUE TITLE
[GBM lr_annealing] failed: water.exceptions.H2OIllegalArgumentException: Can only convert jobs producing a single Model or ModelContainer.

### ISSUE THREAD

**Issue by algomaschine** [h2oai/h2o-tutorials#167]
Dear Developers,

I've got 28 samples of data, the format is exactly the same, numerical and some categorical columns. It's been working continiously (30 min max time per model) and generated various types of models, as you can see there is DeepLearning, GBM, StackedEnsemble variations. All good. Again, each model corresponds to a different data set, but the format is EXACTLY the same.
![image](https://user-images.githubusercontent.com/20881228/200500515-851868f7-d564-43cb-9ed5-65beee4f8bc1.png)

Now, at one instance it shows this error. Unfortunately it doesn't tell me more details. Cou7ld you please advise how can I understand what's happening under the hood and perhaps fix it?
![image](https://user-images.githubusercontent.com/20881228/200500368-371f9e31-826e-4ccc-8712-ef2fa9750ee3.png)

Thank you!

**Comment by algomaschine** [comment]
I also get an 'array out of bounds exception' sometimes, but it continues and eventually generates a model
![image](https://user-images.githubusercontent.com/20881228/200776268-c5e9a19b-450d-4021-b6ae-b5d61fa63b39.png)

**Comment by algomaschine** [comment]
**AutoML progress: |████                                                           |   6%
10:00:16.97: GLM_1_AutoML_4_20221109_95959 [GLM def_1] failed: java.lang.ArrayIndexOutOfBoundsException: 324

AutoML progress: |██████████████████████████████████████████████████████████████▎|  98%
10:29:38.439: GBM_lr_annealing_selection_AutoML_4_20221109_95959 [GBM lr_annealing] failed: water.exceptions.H2OIllegalArgumentException: Can only convert jobs producing a single Model or ModelContainer.

AutoML progress: |███████████████████████████████████████████████████████████████ (done)| 100%
Traceback (most recent call last):
  File ".\auto_model_trainer.py", line 298, in <module>
    train_by_data(os.path.dirname(sys.argv[0])+"\\train-test\\","train_*per_2022-11-*.csv",os.path.dirname(sys.argv[0])+"\\h2o models\\", "*AutoML*per_2022-11-*")
  File ".\auto_model_trainer.py", line 110, in train_by_data
    aml.train(y = y, training_frame = train, leaderboard_frame = test)
  File "C:\Program Files\Python37\lib\site-packages\h2o\automl\_estimator.py", line 683, in train
    self._fetch()
  File "C:\Program Files\Python37\lib\site-packages\h2o\automl\_estimator.py", line 712, in _fetch
    state = _fetch_state(self.key)
  File "C:\Program Files\Python37\lib\site-packages\h2o\automl\_base.py", line 354, in _fetch_state
    event_log = _fetch_table(state_json['event_log_table'], key=project_name+"_eventlog", progress_bar=False)
  File "C:\Program Files\Python37\lib\site-packages\h2o\automl\_base.py", line 327, in _fetch_table
    fr = h2o.H2OFrame(table.cell_values, destination_frame=key, column_names=table.col_header, column_types=table.col_types)
  File "C:\Program Files\Python37\lib\site-packages\h2o\frame.py", line 114, in __init__
    column_names, column_types, na_strings, skipped_columns)
  File "C:\Program Files\Python37\lib\site-packages\h2o\frame.py", line 155, in _upload_python_object
    os.remove(tmp_path)  # delete the tmp file
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2\\tmphburp1m8.csv'
Closing connection _sid_9f5e at exit
H2O session _sid_9f5e closed.**

And I'm starting to get this often,  when generating model after model in the same console. These commands below kinda help, but I still have to monitor for every crush. What might be a specific root cause? The resources are OK, enough memory and everything.
taskkill /F /IM "python.exe"
taskkill /F /IM "java.exe"
